-- Load config files
require('thayin.settings')
require('thayin.keybinds')
require('thayin.plugins')
require('thayin.startpage')
require('thayin.autopairs')
require('thayin.autocommand')
require('thayin.cmp')
require('thayin.colourscheme')
require('thayin.comment')
require('thayin.gitsigns')
require('thayin.impatient')
require('thayin.indentline')
require('thayin.lualine')
require('thayin.nvim-tree')
require('thayin.project')
require('thayin.telescope')
require('thayin.toggleterm')
require('thayin.treesitter')
require('thayin.whichkey')
require('thayin.cokeline')
require('thayin.code_runner')
require('thayin.lsp')
--[[ require('thayin.mason') ]]
